events { worker_connections 1024; }

http {
    # Definimos la zona de memoria para la caché
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=mi_cache:10m max_size=1g inactive=60m use_temp_path=off;

    upstream servidores_apache {
        server apache1:80;
        server apache2:80;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://servidores_apache;
            
            # Ajustes de caché
            proxy_cache mi_cache;
            proxy_cache_valid 200 10m;
            
            # Header para saber si la respuesta vino de la caché (HIT) o no (MISS)
            add_header X-Cache-Status $upstream_cache_status;
        }
    }
}